// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_ADDRESSLAYER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_ADDRESSLAYER
void*_Nonnull uniffi_ptiles_ffi_fn_clone_addresslayer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_ADDRESSLAYER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_ADDRESSLAYER
void uniffi_ptiles_ffi_fn_free_addresslayer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_ADDRESSLAYER_OPEN
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_ADDRESSLAYER_OPEN
void*_Nonnull uniffi_ptiles_ffi_fn_constructor_addresslayer_open(RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_ADDRESSLAYER_ADDRESSES_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_ADDRESSLAYER_ADDRESSES_AT
RustBuffer uniffi_ptiles_ffi_fn_method_addresslayer_addresses_at(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_ADDRESSLAYER_FIND_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_ADDRESSLAYER_FIND_ADDRESS
RustBuffer uniffi_ptiles_ffi_fn_method_addresslayer_find_address(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustBuffer housenumber, RustBuffer street, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_ADMINLAYER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_ADMINLAYER
void*_Nonnull uniffi_ptiles_ffi_fn_clone_adminlayer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_ADMINLAYER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_ADMINLAYER
void uniffi_ptiles_ffi_fn_free_adminlayer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_ADMINLAYER_OPEN
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_ADMINLAYER_OPEN
void*_Nonnull uniffi_ptiles_ffi_fn_constructor_adminlayer_open(RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_ADMINLAYER_ADMIN_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_ADMINLAYER_ADMIN_AT
RustBuffer uniffi_ptiles_ffi_fn_method_adminlayer_admin_at(void*_Nonnull ptr, double lat, double lon, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_PTILESLAYER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_PTILESLAYER
void*_Nonnull uniffi_ptiles_ffi_fn_clone_ptileslayer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_PTILESLAYER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_PTILESLAYER
void uniffi_ptiles_ffi_fn_free_ptileslayer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_PTILESLAYER_OPEN
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_PTILESLAYER_OPEN
void*_Nonnull uniffi_ptiles_ffi_fn_constructor_ptileslayer_open(RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_BUILDING
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_BUILDING
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_building(void*_Nonnull ptr, double lat, double lon, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_BUILDINGS_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_BUILDINGS_AT
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_buildings_at(void*_Nonnull ptr, RustBuffer points, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_BUSINESSES_NEAR
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_BUSINESSES_NEAR
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_businesses_near(void*_Nonnull ptr, double lat, double lon, uint8_t ring, double radius_m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CACHED_BLOCK_COUNT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CACHED_BLOCK_COUNT
uint32_t uniffi_ptiles_ffi_fn_method_ptileslayer_cached_block_count(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CAMERAS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CAMERAS
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_cameras(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CAMERAS_SEEING
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CAMERAS_SEEING
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_cameras_seeing(void*_Nonnull ptr, double lat, double lon, uint8_t ring, double range_m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CLEAR_CACHE
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_CLEAR_CACHE
void uniffi_ptiles_ffi_fn_method_ptileslayer_clear_cache(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_COVERS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_COVERS
int8_t uniffi_ptiles_ffi_fn_method_ptileslayer_covers(void*_Nonnull ptr, double lat, double lon, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_METADATA
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_METADATA
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_metadata(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_INTERSECTION
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_INTERSECTION
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_intersection(void*_Nonnull ptr, double lat, double lon, double threshold_m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_INTERSECTIONS_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_INTERSECTIONS_AT
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_intersections_at(void*_Nonnull ptr, RustBuffer points, double threshold_m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_RAIL
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_RAIL
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_rail(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_ROAD
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_ROAD
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_road(void*_Nonnull ptr, double lat, double lon, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_ROADS_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_ROADS_AT
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_roads_at(void*_Nonnull ptr, RustBuffer points, double threshold_m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_STATION
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_STATION
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_station(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_TRAIL
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_TRAIL
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_trail(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_TRAILHEAD
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_NEAREST_TRAILHEAD
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_nearest_trailhead(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_PARK_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_PARK_AT
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_park_at(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_PARKS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_PARKS
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_parks(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_PREFETCH_BBOX
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_PREFETCH_BBOX
uint32_t uniffi_ptiles_ffi_fn_method_ptileslayer_prefetch_bbox(void*_Nonnull ptr, double min_lat, double min_lon, double max_lat, double max_lon, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_RAIL
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_RAIL
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_rail(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_ROADS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_ROADS
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_roads(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_SEARCH_BUSINESS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_SEARCH_BUSINESS
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_search_business(void*_Nonnull ptr, RustBuffer query, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_TRAILS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_TRAILS
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_trails(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_WATER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_WATER
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_water(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_WATER_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESLAYER_WATER_AT
RustBuffer uniffi_ptiles_ffi_fn_method_ptileslayer_water_at(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_PTILESSTACK
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_PTILESSTACK
void*_Nonnull uniffi_ptiles_ffi_fn_clone_ptilesstack(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_PTILESSTACK
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_PTILESSTACK
void uniffi_ptiles_ffi_fn_free_ptilesstack(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_PTILESSTACK_NEW
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_PTILESSTACK_NEW
void*_Nonnull uniffi_ptiles_ffi_fn_constructor_ptilesstack_new(RustBuffer roads, RustBuffer buildings, RustBuffer business, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_PTILESSTACK_WITH_LAYERS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_PTILESSTACK_WITH_LAYERS
void*_Nonnull uniffi_ptiles_ffi_fn_constructor_ptilesstack_with_layers(RustBuffer roads, RustBuffer buildings, RustBuffer business, RustBuffer trails, RustBuffer parks, RustBuffer water, RustBuffer camera, RustBuffer addresses, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESSTACK_CAMERAS_SEEING
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESSTACK_CAMERAS_SEEING
RustBuffer uniffi_ptiles_ffi_fn_method_ptilesstack_cameras_seeing(void*_Nonnull ptr, double lat, double lon, uint8_t ring, double range_m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESSTACK_LOCATE
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESSTACK_LOCATE
RustBuffer uniffi_ptiles_ffi_fn_method_ptilesstack_locate(void*_Nonnull ptr, double lat, double lon, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESSTACK_SCORE
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_PTILESSTACK_SCORE
RustBuffer uniffi_ptiles_ffi_fn_method_ptilesstack_score(void*_Nonnull ptr, RustBuffer fix, uint8_t ring, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_VOTEDEBOUNCER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CLONE_VOTEDEBOUNCER
void*_Nonnull uniffi_ptiles_ffi_fn_clone_votedebouncer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_VOTEDEBOUNCER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FREE_VOTEDEBOUNCER
void uniffi_ptiles_ffi_fn_free_votedebouncer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_VOTEDEBOUNCER_NEW
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_CONSTRUCTOR_VOTEDEBOUNCER_NEW
void*_Nonnull uniffi_ptiles_ffi_fn_constructor_votedebouncer_new(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_CONFIG
RustBuffer uniffi_ptiles_ffi_fn_method_votedebouncer_config(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_CURRENT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_CURRENT
RustBuffer uniffi_ptiles_ffi_fn_method_votedebouncer_current(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_TICK
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_TICK
RustBuffer uniffi_ptiles_ffi_fn_method_votedebouncer_tick(void*_Nonnull ptr, RustBuffer vote, uint64_t now_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_TICK_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_METHOD_VOTEDEBOUNCER_TICK_AT
RustBuffer uniffi_ptiles_ffi_fn_method_votedebouncer_tick_at(void*_Nonnull ptr, RustBuffer vote, uint64_t now_ms, RustBuffer control, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_ACCEL_STATS_FROM_SAMPLES
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_ACCEL_STATS_FROM_SAMPLES
RustBuffer uniffi_ptiles_ffi_fn_func_accel_stats_from_samples(RustBuffer x, RustBuffer y, RustBuffer z, uint32_t sample_rate_hz, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_CLASSIFY_MOVEMENT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_CLASSIFY_MOVEMENT
RustBuffer uniffi_ptiles_ffi_fn_func_classify_movement(RustBuffer inst_speed_mps, RustBuffer gps_accuracy_m, RustBuffer nearest_road, RustBuffer accel, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_CLASSIFY_MOVEMENT_ACCEL_ONLY
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_CLASSIFY_MOVEMENT_ACCEL_ONLY
RustBuffer uniffi_ptiles_ffi_fn_func_classify_movement_accel_only(RustBuffer accel, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_DEFAULT_DEBOUNCE_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_DEFAULT_DEBOUNCE_CONFIG
RustBuffer uniffi_ptiles_ffi_fn_func_default_debounce_config(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_INTERSECTION_HOLDS_TRAFFIC
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_INTERSECTION_HOLDS_TRAFFIC
int8_t uniffi_ptiles_ffi_fn_func_intersection_holds_traffic(uint8_t intersection_type, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_INTERSECTION_TYPE_NAME
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_INTERSECTION_TYPE_NAME
RustBuffer uniffi_ptiles_ffi_fn_func_intersection_type_name(uint8_t intersection_type, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_MOVEMENT_THRESHOLDS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_MOVEMENT_THRESHOLDS
RustBuffer uniffi_ptiles_ffi_fn_func_movement_thresholds(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_TRAIL_IS_DEVELOPED
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_FN_FUNC_TRAIL_IS_DEVELOPED
int8_t uniffi_ptiles_ffi_fn_func_trail_is_developed(RustBuffer trail_type, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_ptiles_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_ptiles_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_FREE
void ffi_ptiles_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_ptiles_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U8
void ffi_ptiles_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U8
void ffi_ptiles_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U8
void ffi_ptiles_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_ptiles_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I8
void ffi_ptiles_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I8
void ffi_ptiles_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I8
void ffi_ptiles_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_ptiles_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U16
void ffi_ptiles_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U16
void ffi_ptiles_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U16
void ffi_ptiles_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_ptiles_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I16
void ffi_ptiles_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I16
void ffi_ptiles_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I16
void ffi_ptiles_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_ptiles_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U32
void ffi_ptiles_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U32
void ffi_ptiles_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U32
void ffi_ptiles_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_ptiles_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I32
void ffi_ptiles_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I32
void ffi_ptiles_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I32
void ffi_ptiles_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_ptiles_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_U64
void ffi_ptiles_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_U64
void ffi_ptiles_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_U64
void ffi_ptiles_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_ptiles_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_I64
void ffi_ptiles_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_I64
void ffi_ptiles_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_I64
void ffi_ptiles_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_ptiles_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_F32
void ffi_ptiles_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_F32
void ffi_ptiles_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_F32
void ffi_ptiles_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_ptiles_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_F64
void ffi_ptiles_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_F64
void ffi_ptiles_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_F64
void ffi_ptiles_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_ptiles_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_POINTER
void ffi_ptiles_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_ptiles_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_POINTER
void ffi_ptiles_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_ptiles_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_ptiles_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_ptiles_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_ptiles_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_ptiles_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_POLL_VOID
void ffi_ptiles_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_ptiles_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_FREE_VOID
void ffi_ptiles_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_ptiles_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_ACCEL_STATS_FROM_SAMPLES
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_ACCEL_STATS_FROM_SAMPLES
uint16_t uniffi_ptiles_ffi_checksum_func_accel_stats_from_samples(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_CLASSIFY_MOVEMENT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_CLASSIFY_MOVEMENT
uint16_t uniffi_ptiles_ffi_checksum_func_classify_movement(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_CLASSIFY_MOVEMENT_ACCEL_ONLY
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_CLASSIFY_MOVEMENT_ACCEL_ONLY
uint16_t uniffi_ptiles_ffi_checksum_func_classify_movement_accel_only(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_DEFAULT_DEBOUNCE_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_DEFAULT_DEBOUNCE_CONFIG
uint16_t uniffi_ptiles_ffi_checksum_func_default_debounce_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_INTERSECTION_HOLDS_TRAFFIC
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_INTERSECTION_HOLDS_TRAFFIC
uint16_t uniffi_ptiles_ffi_checksum_func_intersection_holds_traffic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_INTERSECTION_TYPE_NAME
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_INTERSECTION_TYPE_NAME
uint16_t uniffi_ptiles_ffi_checksum_func_intersection_type_name(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_MOVEMENT_THRESHOLDS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_MOVEMENT_THRESHOLDS
uint16_t uniffi_ptiles_ffi_checksum_func_movement_thresholds(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_TRAIL_IS_DEVELOPED
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_FUNC_TRAIL_IS_DEVELOPED
uint16_t uniffi_ptiles_ffi_checksum_func_trail_is_developed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_ADDRESSLAYER_ADDRESSES_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_ADDRESSLAYER_ADDRESSES_AT
uint16_t uniffi_ptiles_ffi_checksum_method_addresslayer_addresses_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_ADDRESSLAYER_FIND_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_ADDRESSLAYER_FIND_ADDRESS
uint16_t uniffi_ptiles_ffi_checksum_method_addresslayer_find_address(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_ADMINLAYER_ADMIN_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_ADMINLAYER_ADMIN_AT
uint16_t uniffi_ptiles_ffi_checksum_method_adminlayer_admin_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_BUILDING
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_BUILDING
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_building(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_BUILDINGS_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_BUILDINGS_AT
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_buildings_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_BUSINESSES_NEAR
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_BUSINESSES_NEAR
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_businesses_near(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CACHED_BLOCK_COUNT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CACHED_BLOCK_COUNT
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_cached_block_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CAMERAS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CAMERAS
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_cameras(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CAMERAS_SEEING
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CAMERAS_SEEING
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_cameras_seeing(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CLEAR_CACHE
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_CLEAR_CACHE
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_clear_cache(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_COVERS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_COVERS
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_covers(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_METADATA
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_METADATA
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_INTERSECTION
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_INTERSECTION
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_intersection(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_INTERSECTIONS_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_INTERSECTIONS_AT
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_intersections_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_RAIL
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_RAIL
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_rail(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_ROAD
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_ROAD
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_road(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_ROADS_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_ROADS_AT
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_roads_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_STATION
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_STATION
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_station(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_TRAIL
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_TRAIL
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_trail(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_TRAILHEAD
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_NEAREST_TRAILHEAD
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_nearest_trailhead(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_PARK_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_PARK_AT
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_park_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_PARKS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_PARKS
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_parks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_PREFETCH_BBOX
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_PREFETCH_BBOX
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_prefetch_bbox(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_RAIL
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_RAIL
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_rail(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_ROADS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_ROADS
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_roads(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_SEARCH_BUSINESS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_SEARCH_BUSINESS
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_search_business(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_TRAILS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_TRAILS
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_trails(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_WATER
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_WATER
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_water(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_WATER_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESLAYER_WATER_AT
uint16_t uniffi_ptiles_ffi_checksum_method_ptileslayer_water_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESSTACK_CAMERAS_SEEING
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESSTACK_CAMERAS_SEEING
uint16_t uniffi_ptiles_ffi_checksum_method_ptilesstack_cameras_seeing(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESSTACK_LOCATE
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESSTACK_LOCATE
uint16_t uniffi_ptiles_ffi_checksum_method_ptilesstack_locate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESSTACK_SCORE
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_PTILESSTACK_SCORE
uint16_t uniffi_ptiles_ffi_checksum_method_ptilesstack_score(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_CONFIG
uint16_t uniffi_ptiles_ffi_checksum_method_votedebouncer_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_CURRENT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_CURRENT
uint16_t uniffi_ptiles_ffi_checksum_method_votedebouncer_current(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_TICK
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_TICK
uint16_t uniffi_ptiles_ffi_checksum_method_votedebouncer_tick(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_TICK_AT
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_METHOD_VOTEDEBOUNCER_TICK_AT
uint16_t uniffi_ptiles_ffi_checksum_method_votedebouncer_tick_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_ADDRESSLAYER_OPEN
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_ADDRESSLAYER_OPEN
uint16_t uniffi_ptiles_ffi_checksum_constructor_addresslayer_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_ADMINLAYER_OPEN
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_ADMINLAYER_OPEN
uint16_t uniffi_ptiles_ffi_checksum_constructor_adminlayer_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_PTILESLAYER_OPEN
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_PTILESLAYER_OPEN
uint16_t uniffi_ptiles_ffi_checksum_constructor_ptileslayer_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_PTILESSTACK_NEW
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_PTILESSTACK_NEW
uint16_t uniffi_ptiles_ffi_checksum_constructor_ptilesstack_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_PTILESSTACK_WITH_LAYERS
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_PTILESSTACK_WITH_LAYERS
uint16_t uniffi_ptiles_ffi_checksum_constructor_ptilesstack_with_layers(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_VOTEDEBOUNCER_NEW
#define UNIFFI_FFIDEF_UNIFFI_PTILES_FFI_CHECKSUM_CONSTRUCTOR_VOTEDEBOUNCER_NEW
uint16_t uniffi_ptiles_ffi_checksum_constructor_votedebouncer_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PTILES_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_PTILES_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_ptiles_ffi_uniffi_contract_version(void
    
);
#endif

