//! Golden tests: core decoders vs. the Python reference (`ptiles/*.py`),
//! generated by `test-fixtures/extract_golden.py` into
//! `test-fixtures/golden/<layer>.{block.bin,golden.json,meta.json}`.
//!
//! Field-by-field comparison against `serde_json::Value`, tolerant of
//! float noise (1e-9 abs/rel) since the Python side round-trips through
//! `round()`/tuple construction that can differ in the last bit from
//! Rust's `f64` arithmetic on the same inputs.

use serde_json::{json, Value};
use std::fs;
use std::path::PathBuf;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("test-fixtures")
        .join("golden")
}

fn load_block(layer: &str) -> Vec<u8> {
    fs::read(fixture_dir().join(format!("{layer}.block.bin")))
        .unwrap_or_else(|e| panic!("failed to read {layer}.block.bin: {e}"))
}

fn load_golden(layer: &str) -> Value {
    let text = fs::read_to_string(fixture_dir().join(format!("{layer}.golden.json")))
        .unwrap_or_else(|e| panic!("failed to read {layer}.golden.json: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse {layer}.golden.json: {e}"))
}

fn load_meta(layer: &str) -> Value {
    let text = fs::read_to_string(fixture_dir().join(format!("{layer}.meta.json")))
        .unwrap_or_else(|e| panic!("failed to read {layer}.meta.json: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse {layer}.meta.json: {e}"))
}

/// Recursively compare two JSON values, tolerating float noise. Panics with
/// a path-annotated message on the first mismatch found.
fn assert_json_eq(actual: &Value, expected: &Value, path: &str) {
    match (actual, expected) {
        (Value::Number(a), Value::Number(e)) => {
            let (af, ef) = (a.as_f64().unwrap(), e.as_f64().unwrap());
            let tol = 1e-9_f64.max(ef.abs() * 1e-9);
            assert!(
                (af - ef).abs() <= tol,
                "{path}: number mismatch: actual={af} expected={ef}"
            );
        }
        (Value::Array(a), Value::Array(e)) => {
            assert_eq!(
                a.len(),
                e.len(),
                "{path}: array length mismatch: actual={} expected={}",
                a.len(),
                e.len()
            );
            for (i, (av, ev)) in a.iter().zip(e.iter()).enumerate() {
                assert_json_eq(av, ev, &format!("{path}[{i}]"));
            }
        }
        (Value::Object(a), Value::Object(e)) => {
            let mut a_keys: Vec<_> = a.keys().collect();
            let mut e_keys: Vec<_> = e.keys().collect();
            a_keys.sort();
            e_keys.sort();
            assert_eq!(a_keys, e_keys, "{path}: object key set mismatch");
            for k in e.keys() {
                assert_json_eq(&a[k], &e[k], &format!("{path}.{k}"));
            }
        }
        (a, e) => {
            assert_eq!(a, e, "{path}: value mismatch");
        }
    }
}

#[test]
fn water_golden() {
    let block = load_block("water");
    let golden = load_golden("water");
    let features = ptiles_core::decode_water(&block).expect("decode_water failed");

    let actual = json!({
        "features": features.iter().map(|f| json!({
            "osm_id": f.osm_id,
            "geom_type": match f.geom_type { 0 => "polygon", 1 => "linestring", 2 => "reference", _ => "unknown" },
            "water_type": f.water_type,
            "coords": f.coords,
            "ref_feature_id": f.ref_feature_id,
            "name": f.name,
            "width": f.width,
            "vertex_count": f.coords.len(),
        })).collect::<Vec<_>>(),
    });

    assert_json_eq(&actual, &golden, "water");
}

#[test]
fn parks_golden() {
    let block = load_block("parks");
    let golden = load_golden("parks");
    let features = ptiles_core::decode_parks(&block).expect("decode_parks failed");

    let actual = json!({
        "features": features.iter().map(|f| json!({
            "osm_id": f.osm_id,
            "park_type": f.park_type,
            "coords": f.coords,
            "name": f.name,
        })).collect::<Vec<_>>(),
    });

    assert_json_eq(&actual, &golden, "parks");
}

#[test]
fn rail_golden() {
    let block = load_block("rail");
    let golden = load_golden("rail");
    let features = ptiles_core::decode_rail(&block).expect("decode_rail failed");

    let actual = json!({
        "features": features.iter().map(|f| json!({
            "osm_id": f.osm_id,
            "rail_type": f.rail_type,
            "geom_type": f.geom_type,
            "coords": f.coords,
            "name": f.name,
        })).collect::<Vec<_>>(),
    });

    assert_json_eq(&actual, &golden, "rail");
}

#[test]
fn roads_golden() {
    let block = load_block("roads");
    let golden = load_golden("roads");
    let meta = load_meta("roads");
    let version = meta["file_version"].as_u64().unwrap() as u8;

    let (roads, intersections) =
        ptiles_core::decode_road_block(&block, version).expect("decode_road_block failed");

    let actual = json!({
        "roads": roads.iter().map(|r| json!({
            "osm_id": r.osm_id,
            "road_class": r.road_class,
            "coords": r.coords,
            "name": r.name,
            "ref_tag": r.ref_tag,
            "oneway": r.oneway,
            "speed_limit_kmh": r.speed_limit_kmh,
            "lanes": r.lanes,
            "surface": r.surface,
            "bridge_tunnel": r.bridge_tunnel,
        })).collect::<Vec<_>>(),
        "intersections": intersections.iter().map(|i| json!({
            "lon_micro": i.lon_micro,
            "lat_micro": i.lat_micro,
            "intersection_type": i.intersection_type,
        })).collect::<Vec<_>>(),
    });

    assert_json_eq(&actual, &golden, "roads");
}

#[test]
fn buildings_v8_golden() {
    let block = load_block("buildings_v8");
    let golden = load_golden("buildings_v8");
    let meta = load_meta("buildings_v8");
    let cell_center_lat = meta["cell_center_lat"].as_f64().unwrap();
    let cell_center_lon = meta["cell_center_lon"].as_f64().unwrap();

    let buildings = ptiles_core::decode_buildings(&block, cell_center_lat, cell_center_lon)
        .expect("decode_buildings failed");

    let actual = json!({
        "buildings": buildings.iter().map(|b| json!({
            "osm_id": b.osm_id,
            "building_type": b.building_type,
            "centroid_lat": b.centroid_lat,
            "centroid_lon": b.centroid_lon,
            "coordinates": b.coords,
            "name": b.name,
            "category": b.category,
            "name_source": b.name_source,
            "poi_osm_id": b.poi_osm_id,
        })).collect::<Vec<_>>(),
    });

    assert_json_eq(&actual, &golden, "buildings_v8");
}

#[test]
fn business_golden() {
    let block = load_block("business");
    let golden = load_golden("business");
    let businesses = ptiles_core::decode_business(&block).expect("decode_business failed");

    let actual = json!({
        "businesses": businesses.iter().map(|b| json!({
            "osm_id": b.osm_id,
            "lon": b.lon,
            "lat": b.lat,
            "name": b.name,
            "category_idx": b.category_idx,
            "phone": b.phone,
            "website": b.website,
            "address": b.address,
            "brand": b.brand,
            "operating_status": b.operating_status,
            "emails": b.emails,
            "socials": b.socials,
        })).collect::<Vec<_>>(),
    });

    assert_json_eq(&actual, &golden, "business");
}
